server:
  port: 8080

spring:
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true 
    serialization: 
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_IGNORED_PROPERTIES: false
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ACCEPT_SINGLE_VALUE_AS_ARRAY: true


  datasource:
    platform: postgres
    url: jdbc:postgresql://postgres:5432/testdb
    username: postgres
    password: password
    
  jpa:
    openInView: false
    show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true

  data:
    jpa:
      repositories.enabled: true

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    com.example: DEBUG
  file:
    name: app.log
    